/** \file
 *  This C header file was generated by $ANTLR version 3.2 Sep 23, 2009 12:02:23
 *
 *     -  From the grammar source file : Guolice.g
 *     -                            On : 2010-12-22 16:48:11
 *     -                 for the lexer : GuoliceLexerLexer *
 * Editing it, at least manually, is not wise. 
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
 * The lexer GuoliceLexer has the callable functions (rules) shown below,
 * which will invoke the code for the associated rule in the source grammar
 * assuming that the input stream is pointing to a token/text stream that could begin
 * this rule.
 * 
 * For instance if you call the first (topmost) rule in a parser grammar, you will
 * get the results of a full parse, but calling a rule half way through the grammar will
 * allow you to pass part of a full token stream to the parser, such as for syntax checking
 * in editors and so on.
 *
 * The parser entry points are called indirectly (by function pointer to function) via
 * a parser context typedef pGuoliceLexer, which is returned from a call to GuoliceLexerNew().
 *
 * As this is a generated lexer, it is unlikely you will call it 'manually'. However
 * the methods are provided anyway.
 * * The methods in pGuoliceLexer are  as follows:
 *
 *  -  void      pGuoliceLexer->T__11(pGuoliceLexer)
 *  -  void      pGuoliceLexer->T__12(pGuoliceLexer)
 *  -  void      pGuoliceLexer->T__13(pGuoliceLexer)
 *  -  void      pGuoliceLexer->T__14(pGuoliceLexer)
 *  -  void      pGuoliceLexer->T__15(pGuoliceLexer)
 *  -  void      pGuoliceLexer->T__16(pGuoliceLexer)
 *  -  void      pGuoliceLexer->T__17(pGuoliceLexer)
 *  -  void      pGuoliceLexer->T__18(pGuoliceLexer)
 *  -  void      pGuoliceLexer->T__19(pGuoliceLexer)
 *  -  void      pGuoliceLexer->T__20(pGuoliceLexer)
 *  -  void      pGuoliceLexer->T__21(pGuoliceLexer)
 *  -  void      pGuoliceLexer->T__22(pGuoliceLexer)
 *  -  void      pGuoliceLexer->T__23(pGuoliceLexer)
 *  -  void      pGuoliceLexer->T__24(pGuoliceLexer)
 *  -  void      pGuoliceLexer->T__25(pGuoliceLexer)
 *  -  void      pGuoliceLexer->T__26(pGuoliceLexer)
 *  -  void      pGuoliceLexer->T__27(pGuoliceLexer)
 *  -  void      pGuoliceLexer->T__28(pGuoliceLexer)
 *  -  void      pGuoliceLexer->T__29(pGuoliceLexer)
 *  -  void      pGuoliceLexer->T__30(pGuoliceLexer)
 *  -  void      pGuoliceLexer->T__31(pGuoliceLexer)
 *  -  void      pGuoliceLexer->T__32(pGuoliceLexer)
 *  -  void      pGuoliceLexer->T__33(pGuoliceLexer)
 *  -  void      pGuoliceLexer->T__34(pGuoliceLexer)
 *  -  void      pGuoliceLexer->T__35(pGuoliceLexer)
 *  -  void      pGuoliceLexer->T__36(pGuoliceLexer)
 *  -  void      pGuoliceLexer->T__37(pGuoliceLexer)
 *  -  void      pGuoliceLexer->T__38(pGuoliceLexer)
 *  -  void      pGuoliceLexer->T__39(pGuoliceLexer)
 *  -  void      pGuoliceLexer->T__40(pGuoliceLexer)
 *  -  void      pGuoliceLexer->T__41(pGuoliceLexer)
 *  -  void      pGuoliceLexer->T__42(pGuoliceLexer)
 *  -  void      pGuoliceLexer->T__43(pGuoliceLexer)
 *  -  void      pGuoliceLexer->T__44(pGuoliceLexer)
 *  -  void      pGuoliceLexer->T__45(pGuoliceLexer)
 *  -  void      pGuoliceLexer->T__46(pGuoliceLexer)
 *  -  void      pGuoliceLexer->T__47(pGuoliceLexer)
 *  -  void      pGuoliceLexer->T__48(pGuoliceLexer)
 *  -  void      pGuoliceLexer->T__49(pGuoliceLexer)
 *  -  void      pGuoliceLexer->T__50(pGuoliceLexer)
 *  -  void      pGuoliceLexer->T__51(pGuoliceLexer)
 *  -  void      pGuoliceLexer->T__52(pGuoliceLexer)
 *  -  void      pGuoliceLexer->T__53(pGuoliceLexer)
 *  -  void      pGuoliceLexer->T__54(pGuoliceLexer)
 *  -  void      pGuoliceLexer->T__55(pGuoliceLexer)
 *  -  void      pGuoliceLexer->T__56(pGuoliceLexer)
 *  -  void      pGuoliceLexer->T__57(pGuoliceLexer)
 *  -  void      pGuoliceLexer->T__58(pGuoliceLexer)
 *  -  void      pGuoliceLexer->T__59(pGuoliceLexer)
 *  -  void      pGuoliceLexer->T__60(pGuoliceLexer)
 *  -  void      pGuoliceLexer->T__61(pGuoliceLexer)
 *  -  void      pGuoliceLexer->LETTER(pGuoliceLexer)
 *  -  void      pGuoliceLexer->DIGIT(pGuoliceLexer)
 *  -  void      pGuoliceLexer->STRING_LITERAL(pGuoliceLexer)
 *  -  void      pGuoliceLexer->ID(pGuoliceLexer)
 *  -  void      pGuoliceLexer->INTEGER(pGuoliceLexer)
 *  -  void      pGuoliceLexer->COMMENT(pGuoliceLexer)
 *  -  void      pGuoliceLexer->WS(pGuoliceLexer)
 *  -  void      pGuoliceLexer->Tokens(pGuoliceLexer)
 *
 * The return type for any particular rule is of course determined by the source
 * grammar file.
 */
// [The "BSD licence"]
// Copyright (c) 2005-2009 Jim Idle, Temporal Wave LLC
// http://www.temporal-wave.com
// http://www.linkedin.com/in/jimidle
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

#ifndef	_GuoliceLexer_H
#define _GuoliceLexer_H
/* =============================================================================
 * Standard antlr3 C runtime definitions
 */
#include    <antlr3.h>

/* End of standard antlr 3 runtime definitions
 * =============================================================================
 */
 
#ifdef __cplusplus
extern "C" {
#endif

// Forward declare the context typedef so that we can use it before it is
// properly defined. Delegators and delegates (from import statements) are
// interdependent and their context structures contain pointers to each other
// C only allows such things to be declared if you pre-declare the typedef.
//
typedef struct GuoliceLexer_Ctx_struct GuoliceLexer, * pGuoliceLexer;



#ifdef	ANTLR3_WINDOWS
// Disable: Unreferenced parameter,							- Rules with parameters that are not used
//          constant conditional,							- ANTLR realizes that a prediction is always true (synpred usually)
//          initialized but unused variable					- tree rewrite variables declared but not needed
//          Unreferenced local variable						- lexer rule declares but does not always use _type
//          potentially unitialized variable used			- retval always returned from a rule 
//			unreferenced local function has been removed	- susually getTokenNames or freeScope, they can go without warnigns
//
// These are only really displayed at warning level /W4 but that is the code ideal I am aiming at
// and the codegen must generate some of these warnings by necessity, apart from 4100, which is
// usually generated when a parser rule is given a parameter that it does not use. Mostly though
// this is a matter of orthogonality hence I disable that one.
//
#pragma warning( disable : 4100 )
#pragma warning( disable : 4101 )
#pragma warning( disable : 4127 )
#pragma warning( disable : 4189 )
#pragma warning( disable : 4505 )
#pragma warning( disable : 4701 )
#endif

/** Context tracking structure for GuoliceLexer
 */
struct GuoliceLexer_Ctx_struct
{
    /** Built in ANTLR3 context tracker contains all the generic elements
     *  required for context tracking.
     */
    pANTLR3_LEXER    pLexer;


     void (*mT__11)	(struct GuoliceLexer_Ctx_struct * ctx);
     void (*mT__12)	(struct GuoliceLexer_Ctx_struct * ctx);
     void (*mT__13)	(struct GuoliceLexer_Ctx_struct * ctx);
     void (*mT__14)	(struct GuoliceLexer_Ctx_struct * ctx);
     void (*mT__15)	(struct GuoliceLexer_Ctx_struct * ctx);
     void (*mT__16)	(struct GuoliceLexer_Ctx_struct * ctx);
     void (*mT__17)	(struct GuoliceLexer_Ctx_struct * ctx);
     void (*mT__18)	(struct GuoliceLexer_Ctx_struct * ctx);
     void (*mT__19)	(struct GuoliceLexer_Ctx_struct * ctx);
     void (*mT__20)	(struct GuoliceLexer_Ctx_struct * ctx);
     void (*mT__21)	(struct GuoliceLexer_Ctx_struct * ctx);
     void (*mT__22)	(struct GuoliceLexer_Ctx_struct * ctx);
     void (*mT__23)	(struct GuoliceLexer_Ctx_struct * ctx);
     void (*mT__24)	(struct GuoliceLexer_Ctx_struct * ctx);
     void (*mT__25)	(struct GuoliceLexer_Ctx_struct * ctx);
     void (*mT__26)	(struct GuoliceLexer_Ctx_struct * ctx);
     void (*mT__27)	(struct GuoliceLexer_Ctx_struct * ctx);
     void (*mT__28)	(struct GuoliceLexer_Ctx_struct * ctx);
     void (*mT__29)	(struct GuoliceLexer_Ctx_struct * ctx);
     void (*mT__30)	(struct GuoliceLexer_Ctx_struct * ctx);
     void (*mT__31)	(struct GuoliceLexer_Ctx_struct * ctx);
     void (*mT__32)	(struct GuoliceLexer_Ctx_struct * ctx);
     void (*mT__33)	(struct GuoliceLexer_Ctx_struct * ctx);
     void (*mT__34)	(struct GuoliceLexer_Ctx_struct * ctx);
     void (*mT__35)	(struct GuoliceLexer_Ctx_struct * ctx);
     void (*mT__36)	(struct GuoliceLexer_Ctx_struct * ctx);
     void (*mT__37)	(struct GuoliceLexer_Ctx_struct * ctx);
     void (*mT__38)	(struct GuoliceLexer_Ctx_struct * ctx);
     void (*mT__39)	(struct GuoliceLexer_Ctx_struct * ctx);
     void (*mT__40)	(struct GuoliceLexer_Ctx_struct * ctx);
     void (*mT__41)	(struct GuoliceLexer_Ctx_struct * ctx);
     void (*mT__42)	(struct GuoliceLexer_Ctx_struct * ctx);
     void (*mT__43)	(struct GuoliceLexer_Ctx_struct * ctx);
     void (*mT__44)	(struct GuoliceLexer_Ctx_struct * ctx);
     void (*mT__45)	(struct GuoliceLexer_Ctx_struct * ctx);
     void (*mT__46)	(struct GuoliceLexer_Ctx_struct * ctx);
     void (*mT__47)	(struct GuoliceLexer_Ctx_struct * ctx);
     void (*mT__48)	(struct GuoliceLexer_Ctx_struct * ctx);
     void (*mT__49)	(struct GuoliceLexer_Ctx_struct * ctx);
     void (*mT__50)	(struct GuoliceLexer_Ctx_struct * ctx);
     void (*mT__51)	(struct GuoliceLexer_Ctx_struct * ctx);
     void (*mT__52)	(struct GuoliceLexer_Ctx_struct * ctx);
     void (*mT__53)	(struct GuoliceLexer_Ctx_struct * ctx);
     void (*mT__54)	(struct GuoliceLexer_Ctx_struct * ctx);
     void (*mT__55)	(struct GuoliceLexer_Ctx_struct * ctx);
     void (*mT__56)	(struct GuoliceLexer_Ctx_struct * ctx);
     void (*mT__57)	(struct GuoliceLexer_Ctx_struct * ctx);
     void (*mT__58)	(struct GuoliceLexer_Ctx_struct * ctx);
     void (*mT__59)	(struct GuoliceLexer_Ctx_struct * ctx);
     void (*mT__60)	(struct GuoliceLexer_Ctx_struct * ctx);
     void (*mT__61)	(struct GuoliceLexer_Ctx_struct * ctx);
     void (*mLETTER)	(struct GuoliceLexer_Ctx_struct * ctx);
     void (*mDIGIT)	(struct GuoliceLexer_Ctx_struct * ctx);
     void (*mSTRING_LITERAL)	(struct GuoliceLexer_Ctx_struct * ctx);
     void (*mID)	(struct GuoliceLexer_Ctx_struct * ctx);
     void (*mINTEGER)	(struct GuoliceLexer_Ctx_struct * ctx);
     void (*mCOMMENT)	(struct GuoliceLexer_Ctx_struct * ctx);
     void (*mWS)	(struct GuoliceLexer_Ctx_struct * ctx);
     void (*mTokens)	(struct GuoliceLexer_Ctx_struct * ctx);    const char * (*getGrammarFileName)();
    void	    (*free)   (struct GuoliceLexer_Ctx_struct * ctx);
        
};

// Function protoypes for the constructor functions that external translation units
// such as delegators and delegates may wish to call.
//
ANTLR3_API pGuoliceLexer GuoliceLexerNew         (pANTLR3_INPUT_STREAM instream);
ANTLR3_API pGuoliceLexer GuoliceLexerNewSSD      (pANTLR3_INPUT_STREAM instream, pANTLR3_RECOGNIZER_SHARED_STATE state);

/** Symbolic definitions of all the tokens that the lexer will work with.
 * \{
 *
 * Antlr will define EOF, but we can't use that as it it is too common in
 * in C header files and that would be confusing. There is no way to filter this out at the moment
 * so we just undef it here for now. That isn't the value we get back from C recognizers
 * anyway. We are looking for ANTLR3_TOKEN_EOF.
 */
#ifdef	EOF
#undef	EOF
#endif
#ifdef	Tokens
#undef	Tokens
#endif 
#define T__29      29
#define T__28      28
#define T__27      27
#define T__26      26
#define T__25      25
#define T__24      24
#define T__23      23
#define LETTER      7
#define T__22      22
#define T__21      21
#define T__20      20
#define T__61      61
#define ID      4
#define T__60      60
#define EOF      -1
#define T__55      55
#define T__56      56
#define T__19      19
#define T__57      57
#define T__58      58
#define STRING_LITERAL      6
#define T__51      51
#define T__16      16
#define T__52      52
#define T__15      15
#define T__53      53
#define T__18      18
#define T__54      54
#define T__17      17
#define T__12      12
#define T__11      11
#define T__14      14
#define T__13      13
#define T__59      59
#define DIGIT      8
#define COMMENT      9
#define T__50      50
#define INTEGER      5
#define T__42      42
#define T__43      43
#define T__40      40
#define T__41      41
#define T__46      46
#define T__47      47
#define T__44      44
#define T__45      45
#define T__48      48
#define T__49      49
#define T__30      30
#define T__31      31
#define T__32      32
#define T__33      33
#define WS      10
#define T__34      34
#define T__35      35
#define T__36      36
#define T__37      37
#define T__38      38
#define T__39      39
#ifdef	EOF
#undef	EOF
#define	EOF	ANTLR3_TOKEN_EOF
#endif

#ifndef TOKENSOURCE
#define TOKENSOURCE(lxr) lxr->pLexer->rec->state->tokSource
#endif

/* End of token definitions for GuoliceLexer
 * =============================================================================
 */
/** \} */

#ifdef __cplusplus
}
#endif

#endif

/* END - Note:Keep extra line feed to satisfy UNIX systems */
