/** \file
 *  This C header file was generated by $ANTLR version 3.2 Sep 23, 2009 12:02:23
 *
 *     -  From the grammar source file : Guolice.g
 *     -                            On : 2010-12-22 16:48:11
 *     -                for the parser : GuoliceParserParser *
 * Editing it, at least manually, is not wise. 
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
 * The parser GuoliceParser has the callable functions (rules) shown below,
 * which will invoke the code for the associated rule in the source grammar
 * assuming that the input stream is pointing to a token/text stream that could begin
 * this rule.
 * 
 * For instance if you call the first (topmost) rule in a parser grammar, you will
 * get the results of a full parse, but calling a rule half way through the grammar will
 * allow you to pass part of a full token stream to the parser, such as for syntax checking
 * in editors and so on.
 *
 * The parser entry points are called indirectly (by function pointer to function) via
 * a parser context typedef pGuoliceParser, which is returned from a call to GuoliceParserNew().
 *
 * The methods in pGuoliceParser are  as follows:
 *
 *  - void      pGuoliceParser->program(pGuoliceParser)
 *  - void      pGuoliceParser->procedureDec(pGuoliceParser)
 *  - void      pGuoliceParser->functionDec(pGuoliceParser)
 *  - void      pGuoliceParser->parameters(pGuoliceParser)
 *  - Node*      pGuoliceParser->statement(pGuoliceParser)
 *  - Node*      pGuoliceParser->assignmentStatement(pGuoliceParser)
 *  - Node*      pGuoliceParser->constantDecStatement(pGuoliceParser)
 *  - Node*      pGuoliceParser->variableDecStatement(pGuoliceParser)
 *  - Node*      pGuoliceParser->ifStatement(pGuoliceParser)
 *  - Node *      pGuoliceParser->whileStatement(pGuoliceParser)
 *  - Node *      pGuoliceParser->procedureCallStatement(pGuoliceParser)
 *  - GuoliceParser_actualParameters_return      pGuoliceParser->actualParameters(pGuoliceParser)
 *  - void      pGuoliceParser->exitStatement(pGuoliceParser)
 *  - void      pGuoliceParser->returnStatement(pGuoliceParser)
 *  - Node *      pGuoliceParser->term(pGuoliceParser)
 *  - Node *      pGuoliceParser->negation(pGuoliceParser)
 *  - Node *      pGuoliceParser->unary(pGuoliceParser)
 *  - Node*      pGuoliceParser->multdiv(pGuoliceParser)
 *  - Node*      pGuoliceParser->addsub(pGuoliceParser)
 *  - Node*      pGuoliceParser->compare(pGuoliceParser)
 *  - Node*      pGuoliceParser->expression(pGuoliceParser)
 *  - GuoliceParser_type_return      pGuoliceParser->type(pGuoliceParser)
 *  - Node*      pGuoliceParser->guiDecStatement(pGuoliceParser)
 *  - Node*      pGuoliceParser->guiTerm(pGuoliceParser)
 *  - Node*      pGuoliceParser->guiPositionExpression(pGuoliceParser)
 *  - Node*      pGuoliceParser->guiComparisonExpression(pGuoliceParser)
 *  - Node*      pGuoliceParser->guiStatement(pGuoliceParser)
 *  - Node*      pGuoliceParser->evntHandleStatement(pGuoliceParser)
 *  - GuoliceParser_guiType_return      pGuoliceParser->guiType(pGuoliceParser)
 *  - GuoliceParser_eventType_return      pGuoliceParser->eventType(pGuoliceParser)
 *  - GuoliceParser_positionKeyword_return      pGuoliceParser->positionKeyword(pGuoliceParser)
 *  - GuoliceParser_guiComparsionTerm_return      pGuoliceParser->guiComparsionTerm(pGuoliceParser)
 *
 * The return type for any particular rule is of course determined by the source
 * grammar file.
 */
// [The "BSD licence"]
// Copyright (c) 2005-2009 Jim Idle, Temporal Wave LLC
// http://www.temporal-wave.com
// http://www.linkedin.com/in/jimidle
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

#ifndef	_GuoliceParser_H
#define _GuoliceParser_H
/* =============================================================================
 * Standard antlr3 C runtime definitions
 */
#include    <antlr3.h>

/* End of standard antlr 3 runtime definitions
 * =============================================================================
 */

	#include	<iostream>
	#include	<cstdlib>
	#include	<fstream>
	#include	<string>
	#include	<vector>
	#include	<map>
	#include	<ParseTree.h>
	#include	<Node.h>	
	#include	<FunctionNode.h>

	using namespace std;

 
#ifdef __cplusplus
extern "C" {
#endif

// Forward declare the context typedef so that we can use it before it is
// properly defined. Delegators and delegates (from import statements) are
// interdependent and their context structures contain pointers to each other
// C only allows such things to be declared if you pre-declare the typedef.
//
typedef struct GuoliceParser_Ctx_struct GuoliceParser, * pGuoliceParser;



#ifdef	ANTLR3_WINDOWS
// Disable: Unreferenced parameter,							- Rules with parameters that are not used
//          constant conditional,							- ANTLR realizes that a prediction is always true (synpred usually)
//          initialized but unused variable					- tree rewrite variables declared but not needed
//          Unreferenced local variable						- lexer rule declares but does not always use _type
//          potentially unitialized variable used			- retval always returned from a rule 
//			unreferenced local function has been removed	- susually getTokenNames or freeScope, they can go without warnigns
//
// These are only really displayed at warning level /W4 but that is the code ideal I am aiming at
// and the codegen must generate some of these warnings by necessity, apart from 4100, which is
// usually generated when a parser rule is given a parameter that it does not use. Mostly though
// this is a matter of orthogonality hence I disable that one.
//
#pragma warning( disable : 4100 )
#pragma warning( disable : 4101 )
#pragma warning( disable : 4127 )
#pragma warning( disable : 4189 )
#pragma warning( disable : 4505 )
#pragma warning( disable : 4701 )
#endif
typedef struct GuoliceParser_actualParameters_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;   
    Node * node;
}
    GuoliceParser_actualParameters_return;

typedef struct GuoliceParser_type_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;   
}
    GuoliceParser_type_return;

typedef struct GuoliceParser_guiType_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;   
}
    GuoliceParser_guiType_return;

typedef struct GuoliceParser_eventType_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;   
}
    GuoliceParser_eventType_return;

typedef struct GuoliceParser_positionKeyword_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;   
}
    GuoliceParser_positionKeyword_return;

typedef struct GuoliceParser_guiComparsionTerm_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;   
}
    GuoliceParser_guiComparsionTerm_return;



/** Context tracking structure for GuoliceParser
 */
struct GuoliceParser_Ctx_struct
{
    /** Built in ANTLR3 context tracker contains all the generic elements
     *  required for context tracking.
     */
    pANTLR3_PARSER   pParser;


     void (*program)	(struct GuoliceParser_Ctx_struct * ctx);
     void (*procedureDec)	(struct GuoliceParser_Ctx_struct * ctx);
     void (*functionDec)	(struct GuoliceParser_Ctx_struct * ctx);
     void (*parameters)	(struct GuoliceParser_Ctx_struct * ctx);
     Node* (*statement)	(struct GuoliceParser_Ctx_struct * ctx);
     Node* (*assignmentStatement)	(struct GuoliceParser_Ctx_struct * ctx);
     Node* (*constantDecStatement)	(struct GuoliceParser_Ctx_struct * ctx);
     Node* (*variableDecStatement)	(struct GuoliceParser_Ctx_struct * ctx);
     Node* (*ifStatement)	(struct GuoliceParser_Ctx_struct * ctx);
     Node * (*whileStatement)	(struct GuoliceParser_Ctx_struct * ctx);
     Node * (*procedureCallStatement)	(struct GuoliceParser_Ctx_struct * ctx);
     GuoliceParser_actualParameters_return (*actualParameters)	(struct GuoliceParser_Ctx_struct * ctx);
     void (*exitStatement)	(struct GuoliceParser_Ctx_struct * ctx);
     void (*returnStatement)	(struct GuoliceParser_Ctx_struct * ctx);
     Node * (*term)	(struct GuoliceParser_Ctx_struct * ctx);
     Node * (*negation)	(struct GuoliceParser_Ctx_struct * ctx);
     Node * (*unary)	(struct GuoliceParser_Ctx_struct * ctx);
     Node* (*multdiv)	(struct GuoliceParser_Ctx_struct * ctx);
     Node* (*addsub)	(struct GuoliceParser_Ctx_struct * ctx);
     Node* (*compare)	(struct GuoliceParser_Ctx_struct * ctx);
     Node* (*expression)	(struct GuoliceParser_Ctx_struct * ctx);
     GuoliceParser_type_return (*type)	(struct GuoliceParser_Ctx_struct * ctx);
     Node* (*guiDecStatement)	(struct GuoliceParser_Ctx_struct * ctx);
     Node* (*guiTerm)	(struct GuoliceParser_Ctx_struct * ctx);
     Node* (*guiPositionExpression)	(struct GuoliceParser_Ctx_struct * ctx);
     Node* (*guiComparisonExpression)	(struct GuoliceParser_Ctx_struct * ctx);
     Node* (*guiStatement)	(struct GuoliceParser_Ctx_struct * ctx);
     Node* (*evntHandleStatement)	(struct GuoliceParser_Ctx_struct * ctx);
     GuoliceParser_guiType_return (*guiType)	(struct GuoliceParser_Ctx_struct * ctx);
     GuoliceParser_eventType_return (*eventType)	(struct GuoliceParser_Ctx_struct * ctx);
     GuoliceParser_positionKeyword_return (*positionKeyword)	(struct GuoliceParser_Ctx_struct * ctx);
     GuoliceParser_guiComparsionTerm_return (*guiComparsionTerm)	(struct GuoliceParser_Ctx_struct * ctx);
    // Delegated rules
    const char * (*getGrammarFileName)();
    void	    (*free)   (struct GuoliceParser_Ctx_struct * ctx);
        
};

// Function protoypes for the constructor functions that external translation units
// such as delegators and delegates may wish to call.
//
ANTLR3_API pGuoliceParser GuoliceParserNew         (pANTLR3_COMMON_TOKEN_STREAM instream);
ANTLR3_API pGuoliceParser GuoliceParserNewSSD      (pANTLR3_COMMON_TOKEN_STREAM instream, pANTLR3_RECOGNIZER_SHARED_STATE state);

/** Symbolic definitions of all the tokens that the parser will work with.
 * \{
 *
 * Antlr will define EOF, but we can't use that as it it is too common in
 * in C header files and that would be confusing. There is no way to filter this out at the moment
 * so we just undef it here for now. That isn't the value we get back from C recognizers
 * anyway. We are looking for ANTLR3_TOKEN_EOF.
 */
#ifdef	EOF
#undef	EOF
#endif
#ifdef	Tokens
#undef	Tokens
#endif 
#define T__29      29
#define T__28      28
#define T__27      27
#define T__26      26
#define T__25      25
#define T__24      24
#define LETTER      7
#define T__23      23
#define T__22      22
#define T__21      21
#define T__20      20
#define ID      4
#define T__61      61
#define T__60      60
#define EOF      -1
#define T__55      55
#define T__56      56
#define T__19      19
#define T__57      57
#define T__58      58
#define STRING_LITERAL      6
#define T__51      51
#define T__16      16
#define T__52      52
#define T__15      15
#define T__53      53
#define T__18      18
#define T__54      54
#define T__17      17
#define T__12      12
#define T__11      11
#define T__14      14
#define T__13      13
#define T__59      59
#define DIGIT      8
#define COMMENT      9
#define T__50      50
#define INTEGER      5
#define T__42      42
#define T__43      43
#define T__40      40
#define T__41      41
#define T__46      46
#define T__47      47
#define T__44      44
#define T__45      45
#define T__48      48
#define T__49      49
#define T__30      30
#define T__31      31
#define T__32      32
#define WS      10
#define T__33      33
#define T__34      34
#define T__35      35
#define T__36      36
#define T__37      37
#define T__38      38
#define T__39      39
#ifdef	EOF
#undef	EOF
#define	EOF	ANTLR3_TOKEN_EOF
#endif

#ifndef TOKENSOURCE
#define TOKENSOURCE(lxr) lxr->pLexer->rec->state->tokSource
#endif

/* End of token definitions for GuoliceParser
 * =============================================================================
 */
/** \} */

#ifdef __cplusplus
}
#endif

#endif

/* END - Note:Keep extra line feed to satisfy UNIX systems */
